SET DEFINE OFF;
TRUNCATE TABLE APP_PARAM;
INSERT INTO "APP_PARAM" (PARAM_CODE, PARAM_DESC, ATTRIBUTE_VALUE_C1, ATTRIBUTE_VALUE_C2, ATTRIBUTE_VALUE_C3, ATTRIBUTE_VALUE_C4, ATTRIBUTE_VALUE_C5, ATTRIBUTE_VALUE_N1, ATTRIBUTE_VALUE_N2, ATTRIBUTE_VALUE_N3, ATTRIBUTE_VALUE_D1, ATTRIBUTE_VALUE_D2, LAST_UPDATE_DATE, LAST_UPDATE_USER) VALUES ('AGG_COMPLETE', 'Aggregation completion flag', '0', '0', '0', '0', '0', '0', '0', '0', TO_DATE('2021-03-25', 'YYYY-MM-DD'), TO_DATE('2021-03-25', 'YYYY-MM-DD'), TO_DATE('2021-03-25', 'YYYY-MM-DD'), 'ScoreExtractionApp');
COMMIT;