-- DATA_LOAD package specifications
create or replace PACKAGE        DATA_LOAD AS 
PROCEDURE LOAD_A_SCORE_REQUEST (P_STATUS OUT NUMBER);
PROCEDURE LOAD_B_SCORE_REQUEST (P_STATUS OUT NUMBER);
PROCEDURE MOVE_DATA_STG_SCORE_REQUEST (P_STATUS OUT NUMBER);
PROCEDURE MOVE_DATA_A_SCORE_REQUEST (P_STATUS OUT NUMBER);
PROCEDURE MOVE_DATA_B_SCORE_REQUEST (P_STATUS OUT NUMBER);
PROCEDURE LOAD_STG_SCORE_REQUEST (P_STATUS OUT NUMBER);
END DATA_LOAD;