SET DEFINE OFF;
TRUNCATE TABLE PRODUCT;
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (113,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (0,'OTHER');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (1,'Watani');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (2,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (3,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (4,'Watani');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (5,'Charge Card');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (7,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (10,'Car Leasing');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (15,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (16,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (17,'Watani');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (29,'Watani');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (20,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (36,'Watani');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (37,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (44,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (48,'Car Leasing');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (56,'Car Leasing');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (57,'Car Leasing');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (58,'Watani');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (60,'Revolving_Card');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (63,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (65,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (66,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (67,'Watani');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (68,'Watani');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (70,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (71,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (72,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (74,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (76,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (77,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (78,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (80,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (82,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (83,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (54,'Car Leasing');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (59,'Watani');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (97,'Real Estate');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (105,'Revolving_Card');
Insert into PRODUCT (PRODUCT_CODE,PRODUCT_TYPE) values (109,'Watani');
COMMIT;